# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

# | Vagrant
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


    # base - box
    config.vm.box = "archlinux/base"

    # define / name
    config.vm.define "shocker"

    # hostname
    config.vm.hostname = "shocker"

    # network - adapter - private / host_only
    config.vm.network "private_network", :type => 'dhcp'

    # network - adapter - bridged
    config.vm.network "public_network"

    # provision - ssh
    config.vm.provision "file", source: "../../ssh", destination: "/tmp/ssh"

    # provision - shell - bash
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    config.vm.provision "shell", path: "../../bash/provision.sh"

    # ssh - agent - fowarding
    config.ssh.forward_agent = true

    # | VirtualBox
    config.vm.provider "virtualbox" do |vb|

        # VirtualBox - name
        vb.name = "shocker"

        # VBoxManage - settings
        vb.customize [
            "modifyvm", :id,
            "--memory", "1024",
        ]

    end
    # VirtualBox |


end
# Vagrant |
