# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

# | Vagrant
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


    #| global

        # base - box
        config.vm.box = "archlinux/base"

        # network - adapter - bridged
        config.vm.network "public_network"

        # network - adapter - host only
        config.vm.network "private_network", type: "dhcp"

        # provision - copy - app / bin / ssh
        config.vm.provision "file", source: "../app", destination: "/tmp/app"
        config.vm.provision "file", source: "../bin", destination: "/tmp/bin"
        config.vm.provision "file", source: "ssh",    destination: "/tmp/ssh"

        # provision - shell - bash
        config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
        config.vm.provision "shell", path: "script/provision.sh"

        # ssh - agent - fowarding
        config.ssh.forward_agent = true

        # | VirtualBox
        config.vm.provider "virtualbox" do |vb|

            # VBoxManage - settings
            vb.customize [
                "modifyvm", :id,
                "--memory", "1024",
            ]

        end
        # VirtualBox |

    # global |


    # | machine(s)

        # | shocker
        config.vm.define "shocker" do |web|
            config.vm.hostname = "shocker"
            config.vm.provider :virtualbox do |vb|
                vb.name = "shocker"
                vb.cpus = 2
            end
        end

    # machine(s) |


end
# Vagrant |
